In [2]:
import pandas as pd
import seaborn as sns

sns.set_style("whitegrid")
sns.set_palette("Set2")

In [31]:
RUNS = 24

data_seed_0 = pd.DataFrame()
data_seed_42 = pd.DataFrame()
data_seed_3407 = pd.DataFrame()

grid_seed_0 = pd.read_csv("../outputs/01_grid_mobilenet/seed_0/grid_results.csv")
grid_seed_42 = pd.read_csv("../outputs/01_grid_mobilenet/seed_42/grid_results.csv")
grid_seed_3407 = pd.read_csv("../outputs/01_grid_mobilenet/seed_3407/grid_results.csv")

for run in range(RUNS):
    run_seed_0 = pd.read_json(
        f"../outputs/01_grid_mobilenet/seed_0/run_{run:03d}/epoch_metrics.json"
    )

    run_seed_0["run"] = run
    data_seed_0 = pd.concat([data_seed_0, run_seed_0], ignore_index=True)

    run_seed_42 = pd.read_json(
        f"../outputs/01_grid_mobilenet/seed_42/run_{run:03d}/epoch_metrics.json"
    )
    run_seed_42["run"] = run
    data_seed_42 = pd.concat([data_seed_42, run_seed_42], ignore_index=True)

    run_seed_3407 = pd.read_json(
        f"../outputs/01_grid_mobilenet/seed_3407/run_{run:03d}/epoch_metrics.json"
    )
    run_seed_3407["run"] = run
    data_seed_3407 = pd.concat([data_seed_3407, run_seed_3407], ignore_index=True)

In [33]:
grid_seed_0.sort_values("test_accuracy", ascending=False).head(1)

,run_id,seed,optimizer,batch_size,dropout,weight_decay,best_val_accuracy,best_val_loss,test_accuracy,test_loss
17,17,0,adamw,128,0.5,0.0001,0.481222,1.486949,0.481089,1.483076

In [34]:
grid_seed_42.sort_values("test_accuracy", ascending=False).head(1)

,run_id,seed,optimizer,batch_size,dropout,weight_decay,best_val_accuracy,best_val_loss,test_accuracy,test_loss
16,16,42,adamw,128,0.5,0.0,0.4814,1.445415,0.482122,1.449103

In [35]:
grid_seed_3407.sort_values("test_accuracy", ascending=False).head(1)

,run_id,seed,optimizer,batch_size,dropout,weight_decay,best_val_accuracy,best_val_loss,test_accuracy,test_loss
15,15,3407,adamw,128,0.1,0.0001,0.466811,1.527122,0.466578,1.529676