In [1]:
import pandas as pd
import seaborn as sns

sns.set_style("whitegrid")
sns.set_palette("Set2")

In [2]:
RUNS = 24

data_seed_0 = pd.DataFrame()
data_seed_42 = pd.DataFrame()
data_seed_3407 = pd.DataFrame()

grid_seed_0 = pd.read_csv("../outputs/01_grid_mobilenet/seed_0/grid_results.csv")
grid_seed_42 = pd.read_csv("../outputs/01_grid_mobilenet/seed_42/grid_results.csv")
grid_seed_3407 = pd.read_csv("../outputs/01_grid_mobilenet/seed_3407/grid_results.csv")

for run in range(RUNS):
    run_seed_0 = pd.read_json(
        f"../outputs/01_grid_mobilenet/seed_0/run_{run:03d}/epoch_metrics.json"
    )

    run_seed_0["run"] = run
    data_seed_0 = pd.concat([data_seed_0, run_seed_0], ignore_index=True)

    run_seed_42 = pd.read_json(
        f"../outputs/01_grid_mobilenet/seed_42/run_{run:03d}/epoch_metrics.json"
    )
    run_seed_42["run"] = run
    data_seed_42 = pd.concat([data_seed_42, run_seed_42], ignore_index=True)

    run_seed_3407 = pd.read_json(
        f"../outputs/01_grid_mobilenet/seed_3407/run_{run:03d}/epoch_metrics.json"
    )
    run_seed_3407["run"] = run
    data_seed_3407 = pd.concat([data_seed_3407, run_seed_3407], ignore_index=True)

grid = pd.concat([grid_seed_0, grid_seed_42, grid_seed_3407], ignore_index=True)

In [4]:
grid.columns

Index(['run_id', 'seed', 'optimizer', 'batch_size', 'dropout', 'weight_decay',
       'best_val_accuracy', 'best_val_loss', 'test_accuracy', 'test_loss'],
      dtype='str')

In [5]:
grid.groupby(["optimizer", "batch_size", "dropout", "weight_decay"]).agg(
    {
        "test_accuracy": ["mean", "std"],
        "test_loss": ["mean", "std"],
        "best_val_accuracy": ["mean", "std"],
        "best_val_loss": ["mean", "std"],
    }
).sort_values(("test_accuracy", "mean"), ascending=False)

                                          test_accuracy           test_loss  \
                                                   mean       std      mean
optimizer batch_size dropout weight_decay
adamw     128        0.5     0.0000            0.473833  0.012301  1.469305
                             0.0001            0.473656  0.007980  1.498224
                     0.1     0.0001            0.472015  0.004879  1.500496
                     0.0     0.0000            0.471959  0.009233  1.532615
                             0.0001            0.471015  0.006002  1.510082
                     0.1     0.0000            0.470685  0.007806  1.502150
          256        0.5     0.0001            0.450611  0.006039  1.561926
                             0.0000            0.450404  0.006887  1.597610
                     0.0     0.0001            0.449885  0.008081  1.577900
                             0.0000            0.449819  0.005282  1.560278
                     0.1     0.0001            0.449330  0.007637  1.559310
sgd       128        0.1     0.0001            0.449115  0.009735  1.525890
                     0.5     0.0001            0.448248  0.007604  1.527095
adamw     256        0.1     0.0000            0.447989  0.006269  1.582172
sgd       128        0.0     0.0001            0.446985  0.010023  1.529418
                             0.0000            0.446767  0.007524  1.531072
                     0.1     0.0000            0.445515  0.010170  1.530734
                     0.5     0.0000            0.444844  0.010762  1.531709
          256        0.5     0.0001            0.417144  0.007692  1.591675
                     0.0     0.0000            0.416656  0.008980  1.596266
                     0.5     0.0000            0.415978  0.006998  1.593671
                     0.1     0.0001            0.415763  0.011126  1.594459
                             0.0000            0.415352  0.008644  1.597327
                     0.0     0.0001            0.415230  0.008688  1.597124

                                                    best_val_accuracy  \
                                                std              mean
optimizer batch_size dropout weight_decay
adamw     128        0.5     0.0000        0.025129          0.474785
                             0.0001        0.018692          0.475578
                     0.1     0.0001        0.027904          0.472637
                     0.0     0.0000        0.051170          0.472481
                             0.0001        0.013409          0.472878
                     0.1     0.0000        0.025416          0.470733
          256        0.5     0.0001        0.023983          0.450744
                             0.0000        0.023923          0.451626
                     0.0     0.0001        0.010205          0.451133
                             0.0000        0.031053          0.450037
                     0.1     0.0001        0.012179          0.450244
sgd       128        0.1     0.0001        0.027119          0.450237
                     0.5     0.0001        0.020046          0.449011
adamw     256        0.1     0.0000        0.033442          0.448337
sgd       128        0.0     0.0001        0.025116          0.447685
                             0.0000        0.023650          0.449285
                     0.1     0.0000        0.028908          0.448556
                     0.5     0.0000        0.026243          0.446607
          256        0.5     0.0001        0.020762          0.418381
                     0.0     0.0000        0.021362          0.416104
                     0.5     0.0000        0.018622          0.416548
                     0.1     0.0001        0.025391          0.416048
                             0.0000        0.021635          0.416156
                     0.0     0.0001        0.022794          0.416596

                                                    best_val_loss
                                                std          mean       std
optimizer batch_size dropout weight_decay
adamw     128        0.5     0.0000        0.011323      1.465879  0.025701
                             0.0001        0.008330      1.495537  0.017284
                     0.1     0.0001        0.005247      1.496708  0.028646
                     0.0     0.0000        0.008087      1.529497  0.050094
                             0.0001        0.005474      1.506237  0.012993
                     0.1     0.0000        0.006950      1.500876  0.021513
          256        0.5     0.0001        0.006381      1.559725  0.019425
                             0.0000        0.006378      1.595144  0.025847
                     0.0     0.0001        0.006609      1.575106  0.009487
                             0.0000        0.004804      1.560366  0.030803
                     0.1     0.0001        0.005679      1.557905  0.013330
sgd       128        0.1     0.0001        0.007856      1.521530  0.025442
                     0.5     0.0001        0.006640      1.523444  0.021030
adamw     256        0.1     0.0000        0.005459      1.583203  0.035869
sgd       128        0.0     0.0001        0.008654      1.526737  0.028560
                             0.0000        0.007532      1.527705  0.022945
                     0.1     0.0000        0.010593      1.525633  0.030301
                     0.5     0.0000        0.009574      1.528914  0.024824
          256        0.5     0.0001        0.007176      1.589198  0.020058
                     0.0     0.0000        0.010367      1.595790  0.021454
                     0.5     0.0000        0.007059      1.592932  0.016321
                     0.1     0.0001        0.009704      1.593781  0.024603
                             0.0000        0.009255      1.595123  0.022121
                     0.0     0.0001        0.007900      1.596313  0.021343

In [8]:
grid_seed_0.sort_values("test_accuracy", ascending=False).head(1)

,run_id,seed,optimizer,batch_size,dropout,weight_decay,best_val_accuracy,best_val_loss,test_accuracy,test_loss
17,17,0,adamw,128,0.5,0.0001,0.481222,1.486949,0.481089,1.483076

In [9]:
grid_seed_42.sort_values("test_accuracy", ascending=False).head(1)

,run_id,seed,optimizer,batch_size,dropout,weight_decay,best_val_accuracy,best_val_loss,test_accuracy,test_loss
16,16,42,adamw,128,0.5,0.0,0.4814,1.445415,0.482122,1.449103

In [10]:
grid_seed_3407.sort_values("test_accuracy", ascending=False).head(1)

,run_id,seed,optimizer,batch_size,dropout,weight_decay,best_val_accuracy,best_val_loss,test_accuracy,test_loss
15,15,3407,adamw,128,0.1,0.0001,0.466811,1.527122,0.466578,1.529676